/** `Env` is generated by `wrangler types` (worker-configuration.d.ts). */
export type Bindings = Env

export type AppEnv = { Bindings: Bindings }

/**
 * Reads the Worker Secret referenced by `channels.secret_name`.
 * Secrets are registered with `wrangler secret put <NAME>` and never appear in the wrangler config.
 */
export const readSecret = (env: Bindings, name: string): string | undefined => {
  const value = (env as unknown as Record<string, unknown>)[name]
  return typeof value === 'string' && value.length > 0 ? value : undefined
}
